### ISSUE TITLE
Issue with compiling shaders on Windows and AMD GPUs

### ISSUE THREAD

**Issue by ghost** [basysKom/RiveQtQuickPlugin#4]
The plugin does not render anything with the following runtime error:

`Failed to link shader program: Error: Fail to build reflection info.`

Apparently, there is an error with current AMD Drivers that is addressed here, but not fixed:
https://community.amd.com/t5/opengl-vulkan/doesn-t-work-glpixeltransferf-and-error-in-shader-on-opengl-with/m-p/611304

**Comment by joka42** [comment]
Found the issue today, while testing on windows.
