### ISSUE TITLE
ERROR RUN RiveQtQuickPlugin

### ISSUE THREAD

**Issue by eritondev-stack** [basysKom/RiveQtQuickPlugin#66]
Hello, how are you?

I'm run app, but show error: 

![image](https://github.com/basysKom/RiveQtQuickPlugin/assets/58184733/88142eb0-cdac-4127-8cfe-01beb6290968)

**Comment by jebos** [comment]
Hey, thanks for your feedback. 

Will take a look at it asap. Looks like some id is either wrong or missing.

**Comment by BertholdKrevert** [comment]
Hi,

we are sorry for the inconvenience. Does it work, if you are adding

`QQuickWindow::setGraphicsApi(QSGRendererInterface::Vulkan);`

in your _main.cpp_?

**Comment by BertholdKrevert** [comment]
Fixed in PR #67
