### ISSUE TITLE
ERRO INSTALL RiveQtQuickPlugin QT 5.12.12 USING UBUNTU 22.04 LTS

### ISSUE THREAD

**Issue by eritondev-stack** [basysKom/RiveQtQuickPlugin#68]
Hello, how are you?

I'm error when I run make on QT 5.12.12

`$ cmake -DCMAKE_PREFIX_PATH=~/Qt5.12.12/5.12.12/gcc_64 -S .. -B .`

[ 94%] Automatic MOC and UIC for target sheenbidi
[ 94%] Built target sheenbidi_autogen
[ 94%] Built target sheenbidi
[ 94%] Automatic MOC and UIC for target harfbuzz
[ 94%] Built target harfbuzz_autogen
[ 94%] Built target harfbuzz
[ 94%] Automatic MOC and UIC for target rive_cpp
[ 94%] Built target rive_cpp_autogen
[ 94%] Built target rive_cpp
[ 94%] Automatic MOC and UIC for target harfbuzz-subset
[ 94%] Built target harfbuzz-subset_autogen
[ 94%] Built target harfbuzz-subset
[ 94%] Automatic MOC and UIC for target RiveQtQuickPlugin
[ 94%] Built target RiveQtQuickPlugin_autogen
[ 94%] Building CXX object src/RiveQtQuickItem/CMakeFiles/RiveQtQuickPlugin.dir/RiveQtQuickPlugin_autogen/mocs_compilation.cpp.o
In file included from /home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/../../../../../src/RiveQtQuickItem/riveqtquickitem.h:21,
                 from /home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_riveqtquickitem.cpp:9,
                 from /home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/mocs_compilation.cpp:3:
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/../../../../../src/RiveQtQuickItem/rivestatemachineinput.h:154:5: error: ISO C++ forbids declaration of ‘QML_NAMED_ELEMENT’ with no type [-fpermissive]
  154 |     QML_NAMED_ELEMENT(RiveStateMachineInput)
      |     ^~~~~~~~~~~~~~~~~
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/../../../../../src/RiveQtQuickItem/rivestatemachineinput.h:154:44: error: expected ‘;’ at end of member declaration
  154 |     QML_NAMED_ELEMENT(RiveStateMachineInput)
      |                                            ^
      |                                             ;
In file included from /home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_riveqtquickitem.cpp:9,
                 from /home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/mocs_compilation.cpp:3:
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/../../../../../src/RiveQtQuickItem/riveqtquickitem.h:363:5: error: ‘QML_ELEMENT’ does not name a type
  363 |     QML_ELEMENT
      |     ^~~~~~~~~~~
In file included from /home/eriton/Qt5.12.12/5.12.12/gcc_64/include/QtCore/qobject.h:46,
                 from /home/eriton/Qt5.12.12/5.12.12/gcc_64/include/QtCore/qabstractanimation.h:43,
                 from /home/eriton/Qt5.12.12/5.12.12/gcc_64/include/QtCore/QtCore:6,
                 from /home/eriton/Qt5.12.12/5.12.12/gcc_64/include/QtQml/QtQmlDepends:3,
                 from /home/eriton/Qt5.12.12/5.12.12/gcc_64/include/QtQml/QtQml:3,
                 from /home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/../../../../../src/RiveQtQuickItem/datatypes.h:9,
                 from /home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_datatypes.cpp:9,
                 from /home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/mocs_compilation.cpp:2:
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/../../../../../src/RiveQtQuickItem/riveqtquickitem.h:375:12: error: ‘LoadingStatus’ has not been declared
  375 |     Q_ENUM(LoadingStatus)
      |            ^~~~~~~~~~~~~
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/../../../../../src/RiveQtQuickItem/riveqtquickitem.h:375:12: error: ‘LoadingStatus’ has not been declared
  375 |     Q_ENUM(LoadingStatus)
      |            ^~~~~~~~~~~~~
In file included from /home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_riveqtquickitem.cpp:9,
                 from /home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/mocs_compilation.cpp:3:
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/../../../../../src/RiveQtQuickItem/riveqtquickitem.h:389:5: error: ‘LoadingStatus’ does not name a type
  389 |     LoadingStatus loadingStatus() const;
      |     ^~~~~~~~~~~~~
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/../../../../../src/RiveQtQuickItem/riveqtquickitem.h:492:5: error: ‘LoadingStatus’ does not name a type
  492 |     LoadingStatus m_loadingStatus { Idle };
      |     ^~~~~~~~~~~~~
In file included from /home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/mocs_compilation.cpp:3:
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_riveqtquickitem.cpp:203:33: error: ‘Idle’ is not a member of ‘RiveQtQuickItem’
  203 |       43, uint(RiveQtQuickItem::Idle),
      |                                 ^~~~
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_riveqtquickitem.cpp:204:33: error: ‘Loading’ is not a member of ‘RiveQtQuickItem’
  204 |       44, uint(RiveQtQuickItem::Loading),
      |                                 ^~~~~~~
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_riveqtquickitem.cpp:205:33: error: ‘Loaded’ is not a member of ‘RiveQtQuickItem’
  205 |       45, uint(RiveQtQuickItem::Loaded),
      |                                 ^~~~~~
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_riveqtquickitem.cpp:206:33: error: ‘Error’ is not a member of ‘RiveQtQuickItem’
  206 |       46, uint(RiveQtQuickItem::Error),
      |                                 ^~~~~
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_riveqtquickitem.cpp:207:33: error: ‘Unloading’ is not a member of ‘RiveQtQuickItem’
  207 |       47, uint(RiveQtQuickItem::Unloading),
      |                                 ^~~~~~~~~
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_riveqtquickitem.cpp: In static member function ‘static void RiveQtQuickItem::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)’:
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_riveqtquickitem.cpp:381:36: error: ‘LoadingStatus’ does not name a type
  381 |         case 1: *reinterpret_cast< LoadingStatus*>(_v) = _t->loadingStatus(); break;
      |                                    ^~~~~~~~~~~~~
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_riveqtquickitem.cpp:381:49: error: expected ‘>’ before ‘*’ token
  381 |         case 1: *reinterpret_cast< LoadingStatus*>(_v) = _t->loadingStatus(); break;
      |                                                 ^
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_riveqtquickitem.cpp:381:49: error: expected ‘(’ before ‘*’ token
  381 |         case 1: *reinterpret_cast< LoadingStatus*>(_v) = _t->loadingStatus(); break;
      |                                                 ^
      |                                                 (
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_riveqtquickitem.cpp:381:50: error: expected primary-expression before ‘>’ token
  381 |         case 1: *reinterpret_cast< LoadingStatus*>(_v) = _t->loadingStatus(); break;
      |                                                  ^
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_riveqtquickitem.cpp:381:62: error: ‘class RiveQtQuickItem’ has no member named ‘loadingStatus’; did you mean ‘loadingStatusChanged’?
  381 |         case 1: *reinterpret_cast< LoadingStatus*>(_v) = _t->loadingStatus(); break;
      |                                                              ^~~~~~~~~~~~~
      |                                                              loadingStatusChanged
/home/eriton/Documentos/RiveQtQuickPlugin/build/src/RiveQtQuickItem/RiveQtQuickPlugin_autogen/EWIEGA46WW/moc_riveqtquickitem.cpp:381:77: error: expected ‘)’ before ‘;’ token
  381 |         case 1: *reinterpret_cast< LoadingStatus*>(_v) = _t->loadingStatus(); break;
      |                                                                             ^
      |                                                                             )
make[2]: *** [src/RiveQtQuickItem/CMakeFiles/RiveQtQuickPlugin.dir/build.make:97: src/RiveQtQuickItem/CMakeFiles/RiveQtQuickPlugin.dir/RiveQtQuickPlugin_autogen/mocs_compilation.cpp.o] Erro 1
make[1]: *** [CMakeFiles/Makefile2:407: src/RiveQtQuickItem/CMakeFiles/RiveQtQuickPlugin.dir/all] Erro 2
make: *** [Makefile:136: all] Erro 2

**Comment by jebos** [comment]
Qt 5.12.12 isn't supported by this plugin. I recommend to switch to the most recent Qt5.15.x or (better) to use Qt6.5+
